### PR TITLE
goals

### PR DESCRIPTION
**Pull request by ApoorvaShukla88**

### CODE REVIEW

**Comment by kburd** [comment]
Good to see you are going ahead in the course! I'll try to come up with a more difficult git task for you for the first class

**Comment by ApoorvaShukla88** [comment]
Hi Kaleb, But I wasn't able to add reviewer to that pull request. I was
searching how to do that. But couldn't find as of now.

**Comment by kburd** [comment]
No problem, we'll go over how to do that in class

**Comment by ApoorvaShukla88** [comment]
Also, Can I make my repository private and just share with you?

**Comment by kburd** [comment]
For this repo, certainly. Future repos will be used to show off your abilities. Those we will keep public

**Pull request merged**
